name: Global Monopoly Update
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-python@v4
        with: { python-version: '3.10' }
      - run: pip install huggingface_hub jinja2
      - run: |
          python engine.py
          python generate.py
      - name: Deploy
        run: |
          git config user.name "MonopolyBot"
          git add .
          git commit -m "Auto-update" || exit 0
          git push